import type { AgentSpec } from "@/lib/agent-spec";
import {
  resolveAgentDeployment,
  resolveAgentUi,
  type AgentDeployment,
  type DeploymentFile,
  type DeploymentPlatform,
} from "@/lib/agent-ui";

function buildTypeScriptFile(spec: AgentSpec): DeploymentFile {
  const ui = resolveAgentUi(spec.ui);
  const content = `/**
 * ${spec.name} — TypeScript agent client
 * Generated by Swarm Agent Builder
 */

export interface AgentConfig {
  name: string;
  instructions: string;
  persona: { role: string; tone: string };
  apiEndpoint: string;
}

export const agentConfig: AgentConfig = {
  name: ${JSON.stringify(spec.name)},
  instructions: ${JSON.stringify(spec.instructions)},
  persona: ${JSON.stringify(spec.persona)},
  apiEndpoint: process.env.AGENT_API_URL ?? "http://localhost:3000/api/chat",
};

export interface AgentTheme {
  primaryColor: string;
  mode: "light" | "dark" | "auto";
}

export const agentTheme: AgentTheme = {
  primaryColor: ${JSON.stringify(ui.theme.primaryColor)},
  mode: ${JSON.stringify(ui.theme.mode)},
};

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

export async function sendMessage(
  messages: ChatMessage[]
): Promise<string> {
  const response = await fetch(agentConfig.apiEndpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      messages,
      agentSpec: {
        name: agentConfig.name,
        instructions: agentConfig.instructions,
        persona: agentConfig.persona,
        tools: ${JSON.stringify(spec.tools)},
      },
    }),
  });

  if (!response.ok) {
    throw new Error(\`Agent request failed: \${response.status}\`);
  }

  const data = await response.json();
  return data.reply ?? data.text ?? "";
}
`;

  return { path: "agent-client.ts", language: "typescript", content };
}

function buildPythonFile(spec: AgentSpec): DeploymentFile {
  const ui = resolveAgentUi(spec.ui);
  const content = `"""
${spec.name} — Python agent client
Generated by Swarm Agent Builder
"""

import json
import os
from typing import Any

AGENT_CONFIG = {
    "name": ${JSON.stringify(spec.name)},
    "instructions": ${JSON.stringify(spec.instructions)},
    "persona": ${JSON.stringify(spec.persona)},
    "tools": ${JSON.stringify(spec.tools)},
}

AGENT_THEME = {
    "primary_color": ${JSON.stringify(ui.theme.primaryColor)},
    "mode": ${JSON.stringify(ui.theme.mode)},
}

API_ENDPOINT = os.environ.get("AGENT_API_URL", "http://localhost:3000/api/chat")


def send_message(messages: list[dict[str, str]]) -> str:
    """Send a conversation to the agent runtime and return the reply."""
    import urllib.request

    payload = json.dumps({
        "messages": messages,
        "agentSpec": AGENT_CONFIG,
    }).encode("utf-8")

    req = urllib.request.Request(
        API_ENDPOINT,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    with urllib.request.urlopen(req) as response:
        data = json.loads(response.read().decode("utf-8"))
        return data.get("reply") or data.get("text") or ""


if __name__ == "__main__":
    reply = send_message([{"role": "user", "content": "Hello!"}])
    print(reply)
`;

  return { path: "agent_client.py", language: "python", content };
}

function buildReactFile(spec: AgentSpec): DeploymentFile {
  const ui = resolveAgentUi(spec.ui);
  const welcome = ui.welcomeMessage ?? `Hi! How can I help you today?`;
  const content = `"use client";

import { useState } from "react";

const theme = {
  primary: ${JSON.stringify(ui.theme.primaryColor)},
  bg: ${JSON.stringify(ui.theme.backgroundColor ?? "#0f0f12")},
  mode: ${JSON.stringify(ui.theme.mode)} as const,
};

const starterPrompts = ${JSON.stringify(ui.starterPrompts ?? [])};

export function AgentWidget() {
  const [input, setInput] = useState("");

  return (
    <div
      style={{
        fontFamily: "system-ui, sans-serif",
        background: theme.bg,
        color: theme.mode === "light" ? "#0f172a" : "#f1f5f9",
        borderRadius: "12px",
        overflow: "hidden",
        maxWidth: "720px",
        border: "1px solid rgba(255,255,255,0.08)",
      }}
    >
      <header
        style={{
          padding: "20px 24px",
          background: \`linear-gradient(135deg, \${theme.primary}22, transparent)\`,
        }}
      >
        <h1 style={{ fontSize: 18, fontWeight: 600 }}>${spec.name.replace(/"/g, '\\"')}</h1>
        <p style={{ fontSize: 13, opacity: 0.7, marginTop: 4 }}>
          ${(spec.persona.role || "AI Assistant").replace(/"/g, '\\"')}
        </p>
      </header>

      <main style={{ padding: 24 }}>
        <p style={{ marginBottom: 20, lineHeight: 1.6 }}>${welcome.replace(/"/g, '\\"')}</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {starterPrompts.map((prompt) => (
            <button
              key={prompt}
              type="button"
              onClick={() => setInput(prompt)}
              style={{
                textAlign: "left",
                padding: "12px 16px",
                borderRadius: 8,
                border: "1px solid rgba(255,255,255,0.08)",
                background: "transparent",
                color: "inherit",
                cursor: "pointer",
              }}
            >
              {prompt}
            </button>
          ))}
        </div>
      </main>

      <footer
        style={{
          display: "flex",
          gap: 8,
          padding: "16px 24px",
          borderTop: "1px solid rgba(255,255,255,0.06)",
        }}
      >
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Message ${spec.name.replace(/"/g, '\\"')}…"
          style={{
            flex: 1,
            padding: "10px 14px",
            borderRadius: 8,
            border: "1px solid rgba(255,255,255,0.1)",
            background: "transparent",
            color: "inherit",
          }}
        />
        <button
          type="button"
          style={{
            padding: "10px 18px",
            borderRadius: 8,
            border: "none",
            background: theme.primary,
            color: "white",
            fontWeight: 500,
            cursor: "pointer",
          }}
        >
          Send
        </button>
      </footer>
    </div>
  );
}
`;

  return { path: "AgentWidget.tsx", language: "tsx", content };
}

/** Client SDK files only — HTML frontend is LLM-generated via generateAgentFrontend. */
export function generateDeploymentFiles(
  spec: AgentSpec,
  platform: DeploymentPlatform
): DeploymentFile[] {
  switch (platform) {
    case "html":
      return [];
    case "typescript":
      return [buildTypeScriptFile(spec)];
    case "python":
      return [buildPythonFile(spec)];
    case "react":
      return [buildReactFile(spec), buildTypeScriptFile(spec)];
    default:
      return [];
  }
}

export function syncDeployment(
  spec: AgentSpec,
  platform?: DeploymentPlatform
): AgentDeployment {
  const current = resolveAgentDeployment(spec.deployment);
  const targetPlatform = platform ?? current.platform;
  const preservedHtml = current.files.find((f) => f.path === "index.html");
  const clientFiles = generateDeploymentFiles(spec, targetPlatform);
  const customFiles = current.files.filter(
    (f) =>
      f.path !== "index.html" &&
      !clientFiles.some((g) => g.path === f.path)
  );

  return {
    platform: targetPlatform,
    frontendGenerated: current.frontendGenerated,
    lastFrontendInstruction: current.lastFrontendInstruction,
    files: [
      ...(preservedHtml ? [preservedHtml] : []),
      ...clientFiles,
      ...customFiles.filter((f) => !clientFiles.some((g) => g.path === f.path)),
    ],
  };
}
